"""Public module supporting the AIAS development factory."""
from __future__ import annotations
from dataclasses import dataclass,asdict
from pathlib import Path
import json,re,zipfile,hashlib,subprocess,sys,os
@dataclass(slots=True)
class ModuleSpec:
    """Execute the public ModuleSpec operation for the AIAS development factory using explicit caller inputs."""
    module_id:str; package_name:str; display_name:str; module_type:str; capabilities:list[str]; required_tests:int=200; version:str='1.0.0'
    @classmethod
    def load(cls,path:Path):
        """Load a development module specification from UTF-8 JSON."""
        return cls(**json.loads(path.read_text(encoding='utf-8')))
    def save(self,path:Path):
        """Persist the complete module specification as readable JSON."""
        path.parent.mkdir(parents=True,exist_ok=True); path.write_text(json.dumps(asdict(self),indent=2),encoding='utf-8')
class SpecValidator:
    """Execute the public SpecValidator operation for the AIAS development factory using explicit caller inputs."""
    def validate(self,s):
        """Validate validate for the AIAS development factory and report explicit issues."""
        e=[]
        if not re.fullmatch(r'[A-Z0-9-]{3,64}',s.module_id): e.append('invalid_module_id')
        if not re.fullmatch(r'[a-z][a-z0-9_]*',s.package_name): e.append('invalid_package_name')
        if s.module_type not in {'AMP','ECP','KERNEL','SERVICE','PLUGIN','TOOL'}: e.append('invalid_module_type')
        if not s.capabilities: e.append('missing_capabilities')
        if s.required_tests<1: e.append('invalid_required_tests')
        return e
class DevelopmentFactory:
    """Execute the public DevelopmentFactory operation for the AIAS development factory using explicit caller inputs."""
    def generate(self,s,out:Path):
        """Build the generate required by the AIAS development factory from explicit inputs."""
        e=SpecValidator().validate(s)
        if e: raise ValueError(','.join(e))
        c=''.join(x.capitalize() for x in s.package_name.split('_'))+'Core'; src=out/'src'/s.package_name; tests=out/'tests'; docs=out/'docs'; eng=out/'engineering'/s.module_id.lower()
        for d in (src,tests,docs,eng): d.mkdir(parents=True,exist_ok=True)
        (src/'__init__.py').write_text(f'__version__="{s.version}"\n',encoding='utf-8')
        (src/'core.py').write_text(f"class {c}:\n    def doctor(self): return {{'module_id':'{s.module_id}','status':'READY','capabilities':{s.capabilities!r}}}\n    def validate(self): return True\n",encoding='utf-8')
        (src/'cli.py').write_text(f"import argparse,json\nfrom .core import {c}\ndef main():\n p=argparse.ArgumentParser(); p.add_argument('command',choices=['doctor','validate']); a=p.parse_args(); x={c}(); print(json.dumps(x.doctor() if a.command=='doctor' else {{'passed':x.validate()}},indent=2)); return 0\nif __name__=='__main__': raise SystemExit(main())\n",encoding='utf-8')
        (tests/f'test_{s.package_name}.py').write_text(f"import pytest\nfrom {s.package_name}.core import {c}\n@pytest.mark.parametrize('i',range({s.required_tests}))\ndef test_generated(i):\n x={c}(); assert x.validate(); assert x.doctor()['status']=='READY'\n",encoding='utf-8')
        (docs/f'{s.module_id}_README.md').write_text('# '+s.display_name+'\n\nGenerated by AIAS ADF-001.\n\n'+'\n'.join('- '+x for x in s.capabilities)+'\n',encoding='utf-8')
        (eng/'manifest.json').write_text(json.dumps({'module_id':s.module_id,'package_name':s.package_name,'version':s.version,'module_type':s.module_type,'capabilities':s.capabilities,'required_tests':s.required_tests,'generated_by':'AIAS-ADF-001'},indent=2),encoding='utf-8')
        return {'module_root':str(out),'generated_files':6,'required_tests':s.required_tests}
class QualityGate:
    """Execute the public QualityGate operation for the AIAS development factory using explicit caller inputs."""
    def run(self,r:Path):
        """Execute run for the AIAS development factory with validated state transitions."""
        env=dict(os.environ); env['PYTHONPATH']=str(r/'src'); env['PYTEST_DISABLE_PLUGIN_AUTOLOAD']='1'; p=subprocess.run([sys.executable,'-m','pytest',str(r/'tests'),'-q'],cwd=r,env=env,capture_output=True,text=True)
        return {'passed':p.returncode==0,'stdout':p.stdout,'stderr':p.stderr}
class ReleaseBuilder:
    """Execute the public ReleaseBuilder operation for the AIAS development factory using explicit caller inputs."""
    def build(self,r:Path,d:Path):
        """Build the build required by the AIAS development factory from explicit inputs."""
        d.mkdir(parents=True,exist_ok=True); a=d/f'{r.name}.zip'
        with zipfile.ZipFile(a,'w',zipfile.ZIP_DEFLATED) as z:
            for p in r.rglob('*'):
                if p.is_file() and '__pycache__' not in p.parts and '.pytest_cache' not in p.parts: z.write(p,p.relative_to(r))
        h=hashlib.sha256(a.read_bytes()).hexdigest(); rec=d/f'{r.name}.receipt.json'; rec.write_text(json.dumps({'status':'PASS','archive':str(a),'sha256':h},indent=2),encoding='utf-8'); return {'archive':str(a),'sha256':h,'receipt':str(rec)}
class Orchestrator:
    """Execute the public Orchestrator operation for the AIAS development factory using explicit caller inputs."""
    def execute(self,spec_path:Path,w:Path):
        """Execute execute for the AIAS development factory with validated state transitions."""
        s=ModuleSpec.load(spec_path); r=w/s.module_id; g=DevelopmentFactory().generate(s,r); q=QualityGate().run(r)
        if not q['passed']: raise RuntimeError(q['stdout']+q['stderr'])
        rel=ReleaseBuilder().build(r,w/'release'); result={'validated':True,'generated':g,'qa':{'passed':True},'release':rel}; e=w/'qa'/f'{s.module_id}.json'; e.parent.mkdir(parents=True,exist_ok=True); e.write_text(json.dumps(result,indent=2),encoding='utf-8'); return result
