"""Self-contained HTML rendering for the permanent executive panel."""
from __future__ import annotations
import html,json

def render(data:dict)->str:
 """Render a dependency-free responsive dashboard with embedded evidence."""
 payload=html.escape(json.dumps(data,ensure_ascii=False))
 cards=''.join(f'<article><small>{label}</small><strong>{value}</strong><span>{note}</span></article>' for label,value,note in [
  ("Capital tecnológico",data["capital"]["components"],"componentes registrados"),("Paquetes",data["capital"]["packages"],"capacidades fuente"),("Pruebas",data["capital"]["test_files"],"archivos de prueba"),("Experiencia",f'{data["experience"].get("ux_evidence_percent") or 0}%',data["experience"]["workspace_current"]),("Aceleración",f'{data["acceleration"]["percent"]}%',data["acceleration"]["classification"]),("Madurez referencia",f'L{data["maturity"]["reference_capability_level"]}',data["maturity"].get("campaign_status","NOT_STARTED")),("Compuertas externas",f'{data["external_gates"]["satisfied"]}/{data["external_gates"]["total"]}',f'{data["external_gates"]["evidence_records"]} evidencias · {data["external_gates"]["registered_authorities"]} autoridades')])
 systems=''.join(f'<li><i class="{x["status"].lower()}"></i><div><b>{html.escape(x["name"])}</b><small>{x["status"]}</small></div></li>' for x in data["company_systems"])
 gates=''.join(f'<li><i class="{("operational" if x.get("status")=="SATISFIED" else "waiting")}"></i><div><b>{html.escape(x.get("name",x.get("gate_id","Gate")))}</b><small>{html.escape(x.get("status","UNKNOWN"))} · {html.escape(x.get("next_action",""))}</small></div></li>' for x in data["external_gates"]["items"])
 return f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>AIAS Productivity Dashboard</title><style>
:root{{--bg:#07111d;--panel:#0d1b2a;--line:#1f3850;--cyan:#34d9d0;--green:#73e2a7;--amber:#ffc857;--text:#edf6f9;--muted:#92a8ba}}*{{box-sizing:border-box}}body{{margin:0;background:radial-gradient(circle at 85% 0,#12344b 0,transparent 35%),var(--bg);color:var(--text);font:15px Inter,Segoe UI,sans-serif}}header,main{{max-width:1440px;margin:auto}}header{{padding:32px 28px 20px;display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid var(--line)}}h1{{margin:5px 0;font-size:32px;letter-spacing:-1px}}.eyebrow{{color:var(--cyan);font-weight:700;letter-spacing:2px}}.live{{color:var(--green)}}main{{padding:24px 28px}}.cards{{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}}article,.panel{{background:linear-gradient(145deg,#102337,#0a1725);border:1px solid var(--line);border-radius:14px;box-shadow:0 12px 30px #0004}}article{{padding:18px;min-height:132px}}article small,article span{{display:block;color:var(--muted)}}article strong{{display:block;font-size:30px;margin:16px 0 8px}}.grid{{display:grid;grid-template-columns:1.25fr .75fr;gap:18px;margin-top:18px}}.panel{{padding:22px}}h2{{font-size:18px;margin:0 0 20px}}ul{{list-style:none;padding:0;margin:0;display:grid;grid-template-columns:repeat(2,1fr);gap:9px}}li{{display:flex;gap:12px;align-items:center;padding:12px;background:#081522;border-radius:9px}}li i{{width:9px;height:9px;border-radius:50%;background:var(--amber)}}li i.operational{{background:var(--green)}}li small{{display:block;color:var(--muted);margin-top:3px}}.bar{{height:12px;background:#07101a;border-radius:10px;overflow:hidden;margin:8px 0 18px}}.bar i{{display:block;height:100%;background:linear-gradient(90deg,var(--cyan),var(--green))}}.warning{{color:var(--amber);border-left:3px solid var(--amber);padding:10px 14px;background:#ffc85712}}footer{{max-width:1440px;margin:20px auto;padding:0 28px 30px;color:var(--muted)}}@media(max-width:1000px){{.cards{{grid-template-columns:repeat(3,1fr)}}.grid{{grid-template-columns:1fr}}}}@media(max-width:600px){{.cards{{grid-template-columns:1fr 1fr}}ul{{grid-template-columns:1fr}}}}
</style></head><body><header><div><div class="eyebrow">AIAS // COMMAND CENTER</div><h1>Productivity Dashboard</h1><div>{html.escape(data["roadmap"]["current"])}</div></div><div class="live">● EVIDENCE LIVE</div></header><main><section class="cards">{cards}</section><section class="grid"><div class="panel"><h2>Empresa digital de ingeniería</h2><ul>{systems}</ul></div><div class="panel"><h2>Cobertura documental</h2><b>Módulos — {data["documentation"]["module_percent"]}%</b><div class="bar"><i style="width:{data["documentation"]["module_percent"]}%"></i></div><b>APIs públicas — {data["documentation"]["symbol_percent"]}%</b><div class="bar"><i style="width:{data["documentation"]["symbol_percent"]}%"></i></div><p>Brechas registradas: {data["documentation"]["missing"]}</p><p class="warning">Usabilidad renderizada: pendiente; evidencia técnica UX: {data["experience"].get("ux_evidence_percent") or 0}%.</p><p class="warning">{html.escape(data["maturity"]["warning"] or "Nivel 5 auditado")}</p><h2>Siguiente</h2><p>{html.escape(data["roadmap"]["next"])}</p></div></section><section class="panel" style="margin-top:18px"><h2>Compuertas externas verificables</h2><ul>{gates}</ul></section><script id="aias-evidence" type="application/json">{payload}</script></main><footer>Datos derivados del repositorio. Las estimaciones no sustituyen auditorías ni aprobación profesional.</footer></body></html>'''
